### ISSUE TITLE
Help understanding test errors

### ISSUE THREAD

**Issue by willfaught** [pboyer/antlr4#14]
OK, now that the easy test problems are fixed, I'm digging into failing tests, but having trouble understanding what they mean or how to dig into them. For example:

```
Running org.antlr.v4.test.runtime.go.TestCompositeParsers
dir /var/folders/bx/qk0phsxd265fqj512dnnpg080000gn/T/TestCompositeParsers-1464378084901/parser
antlr reports warnings from [-visitor, -Dlanguage=Go, -o, /var/folders/bx/qk0phsxd265fqj512dnnpg080000gn/T/TestCompositeParsers-1464378084901/parser, -lib, /var/folders/bx/qk0phsxd265fqj512dnnpg080000gn/T/TestCompositeParsers-1464378084901/parser, /var/folders/bx/qk0phsxd265fqj512dnnpg080000gn/T/TestCompositeParsers-1464378084901/parser/M.g4]
Message{errorType=IMPLICIT_TOKEN_DEFINITION, args=[B], e=null, fileName='/var/folders/bx/qk0phsxd265fqj512dnnpg080000gn/T/TestCompositeParsers-1464378084901/parser/M.g4', line=7, charPosition=4}
```

And:

```
dir /var/folders/bx/qk0phsxd265fqj512dnnpg080000gn/T/TestFullContextParsing-1464378174641/parser
exec stderrVacuum: line 1:5 reportAttemptingFullContext d=1 (e), input='34abc'
line 1:2 reportContextSensitivity d=1 (e), input='34'
```

And:

```
testLoopsSimulateTailRecursion(org.antlr.v4.test.runtime.go.TestFullContextParsing)  Time elapsed: 5.841 sec  <<< FAILURE!
java.lang.AssertionError: expected:<line 1:3 reportAttemptingFullContext d=3 (expr_primary), input='a(i)'
line 1:7 reportAmbiguity d=3 (expr_primary): ambigAlts={2, 3}, input='a(i)<-x'
> but was:<null>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:144)
    at org.antlr.v4.test.runtime.go.TestFullContextParsing.testLoopsSimulateTailRecursion(TestFullContextParsing.java:426)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

And:

```
dir /var/folders/bx/qk0phsxd265fqj512dnnpg080000gn/T/TestLeftRecursion-1464378328580/parser
exec stderrVacuum: line 1:12 mismatched input '<EOF>' expecting '>>'
```

I've seen this error before:

```
dir /var/folders/bx/qk0phsxd265fqj512dnnpg080000gn/T/TestLeftRecursion-1464378296039/parser
exec stderrVacuum: # command-line-arguments
/var/folders/bx/qk0phsxd265fqj512dnnpg080000gn/T/TestLeftRecursion-1464378296039/Test.go:32: not enough arguments in call to p.A
```

Looks like for this one, `TContext.A` has zero params, but `TParser.A` has an int param. Is this supposed to be calling `TContext.A` or `TParser.A` (and if so, what should the int be)?

Any tips/insight appreciated!

**Comment by willfaught** [comment]
Also, any easy way to tell which test is failing? I see the file name, but not the method name.

Edit:

E.g. it isn't at all clear that

```
Running org.antlr.v4.test.runtime.go.TestCompositeParsers
dir /var/folders/bx/qk0phsxd265fqj512dnnpg080000gn/T/TestCompositeParsers-1464378084901/parser
antlr reports warnings from [-visitor, -Dlanguage=Go, -o, /var/folders/bx/qk0phsxd265fqj512dnnpg080000gn/T/TestCompositeParsers-1464378084901/parser, -lib, /var/folders/bx/qk0phsxd265fqj512dnnpg080000gn/T/TestCompositeParsers-1464378084901/parser, /var/folders/bx/qk0phsxd265fqj512dnnpg080000gn/T/TestCompositeParsers-1464378084901/parser/M.g4]
Message{errorType=IMPLICIT_TOKEN_DEFINITION, args=[B], e=null, fileName='/var/folders/bx/qk0phsxd265fqj512dnnpg080000gn/T/TestCompositeParsers-1464378084901/parser/M.g4', line=7, charPosition=4}
```

is from test `TestCompositeParsers.testDelegatorAccessesDelegateMembers`.

**Comment by willfaught** [comment]
I'm seeing how it works now. It prints the test class name, then each test method gets its own "dir" line, followed at the end by the test summary. So right now TestCompositeParsers is actually passing, despite that warning in my last post.

**Comment by willfaught** [comment]
The third example in the first post, the one with the stack trace, is apparently part of the failure summary for a test class. Making more sense all the time. ;)

**Comment by pboyer** [comment]
@willfaught It looks like you're grokking things. :D

Thus far, my (naive) debug approach has been to open the created temp directory and debug the code directly by running the `antlr` tool, `go`, and so on. With a little inspection, this helps to determine whether the bug is in the runtime, gen'ed parser, or gen'ed test case.

However, it would be nice to have cleaner test output. There's a fair bit of indirection in the testing code (due to all the codegen), so I'm open to any improvements. A lot of this may just be unfamiliarity with maven and the broader ANTLR code base...

**Comment by jwkohnen** [comment]
Which IDE do you use? I use Intellij IDEA and import this project by its top level `pom.xml` (something something import maven project, then choose antlr4 folder). Then I run `mvn install` until the first go test case runs. Then I cancel maven and IDEA is able to pick up on the test harness that maven has created. Then I can click on the `runtime-testsuite/test/.../runtime/go` folder (bread crumb) and select `Run 'Tests in...'`. Then the test reports are nicely aggregated by the IDE and you can re-run single tests, just like you'd usually do with your IDE. I suppose Netbeans or Eclipse can handle this similarly. 

IDEA has a nice StringTemplate plugin, btw. Very useful. 

Now if only I knew how to tell IDEA that there is a Go project inside a Java project and I would like to use both at the same time, instead of switching the project's SDK globally. That would be great! </meme>

**Comment by willfaught** [comment]
I use TextMate 2. Not much help there, unfortunately. :( There's a way to run individual tests with Maven like `mvn test -Dtest=Class#method`, but it's broken somehow in antlr4.

**Comment by jwkohnen** [comment]
Maybe this could help you: [Run a single test of ANTLR's runtime-testsuite (for bisect)](https://gist.github.com/wjkohnen/e063130f64749e67a724d4e0b0b1d288).

**Comment by willfaught** [comment]
Thanks, I'll give that a try!
